language: node_js
node_js:
  - 14
script:
  - eslint --fix 'src/**'
  - yarn test:coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database vuttrs;' -U postgres
  - yarn run:migrations
