version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: lu1312enzo
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/vuttr-backend
    command: bash -c "yarn install --prod && yarn debug"
    volumes:
      - ./dist/:/usr/src/vuttr-backend/dist/
      - ./package.json:/usr/src/vuttr-backend/package.json
    env_file:
      - .env
    environment:
      TYPEORM_URL: postgres://postgres:lu1312enzo@postgres:5432/vuttr
      TYPEORM_ENTITIES: ./dist/infra/database/typeorm/entities/*.js
    restart: always
    ports:
      - 3000:3000
      - 9222:9222
    links:
      - postgres
