version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: lu1312enzo
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/vuttr-backend
    volumes:
      - ./package.json:/usr/src/vuttr-backend/package.json
      - ./dist:/usr/src/vuttr-backend/dist
    env_file:
      - .env
    environment:
      TYPEORM_URL: postgres://postgres:lu1312enzo@postgres:5432/vuttr
      TYPEORM_ENTITIES: ./dist/infra/database/typeorm/entities/*.js
    command: sh -c "yarn install --prod && yarn start"
    restart: always
    ports:
      - 5050:5050
    links:
      - postgres
